# Generated by Django 3.1.3 on 2020-12-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField()),
                ('moving_average', models.FloatField()),
                ('server_name', models.CharField(max_length=200)),
            ],
        ),
    ]
